# Generated by Django 4.1.3 on 2022-12-20 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrijeme_transakcije', models.DateTimeField(default=django.utils.timezone.now)),
                ('litraza', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=64)),
                ('prezime', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='KrvnaGrupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antigen', models.CharField(choices=[('0', '0'), ('A', 'A'), ('B', 'B'), ('AB', 'AB')], default='0', max_length=2)),
                ('RhFaktor', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Primanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litraza', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='Primatelj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=64)),
                ('prezime', models.CharField(max_length=64)),
            ],
        ),
    ]
