# Generated by Django 4.1.3 on 2022-12-20 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacija',
            name='donator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.donator'),
        ),
        migrations.AddField(
            model_name='donator',
            name='krvna_grupa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.krvnagrupa'),
        ),
        migrations.AddField(
            model_name='primanje',
            name='primatelj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.primatelj'),
        ),
        migrations.AddField(
            model_name='primatelj',
            name='krvna_grupa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.krvnagrupa'),
        ),
    ]
