# Generated by Django 3.2.16 on 2022-12-21 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonacijskaKartica',
            fields=[
                ('donator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.donator')),
            ],
        ),
        migrations.RemoveField(
            model_name='donacija',
            name='id',
        ),
        migrations.RemoveField(
            model_name='donacija',
            name='litraza',
        ),
        migrations.RemoveField(
            model_name='krvnagrupa',
            name='RhFaktor',
        ),
        migrations.RemoveField(
            model_name='krvnagrupa',
            name='antigen',
        ),
        migrations.RemoveField(
            model_name='primanje',
            name='litraza',
        ),
        migrations.AddField(
            model_name='donacija',
            name='donator',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.donator'),
        ),
        migrations.AddField(
            model_name='donator',
            name='krvna_grupa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.krvnagrupa'),
        ),
        migrations.AddField(
            model_name='krvnagrupa',
            name='kg',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='primanje',
            name='primatelj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.primatelj'),
        ),
        migrations.AddField(
            model_name='primatelj',
            name='krvna_grupa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.krvnagrupa'),
        ),
        migrations.CreateModel(
            name='SpremnikKrvi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('krvna_grupa', models.ManyToManyField(to='main.KrvnaGrupa')),
            ],
        ),
        migrations.AddField(
            model_name='donacija',
            name='spremnik_krvi',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.spremnikkrvi'),
        ),
        migrations.AddField(
            model_name='primanje',
            name='spremnik_krvi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.spremnikkrvi'),
        ),
    ]
